from __future__ import annotations

from .models import OfficialRuleProfile


OFFICIAL_RULE_PROFILES: list[OfficialRuleProfile] = [
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-001",
        official_review_point="不得将供应商规模条件、股权结构、年限设置为资格条件",
        official_rule_name="不得将资产总额的隐性限制证书设置为资格条件",
        priority="P0",
        target_data_slots=["资格门槛明细", "资格条件明细", "特定资格要求", "证书材料适用阶段"],
        evidence_patterns=["科技型中小企业", "高新技术企业", "资产总额", "规模类型"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
        report_titles=["不得将资产总额的隐性限制证书设置为资格条件", "资格条件可能缺乏履约必要性或带有歧视性门槛"],
        matching_terms=["隐性限制证书", "规模条件", "资产总额", "科技型中小企业", "高新技术企业"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-002",
        official_review_point="不得将供应商规模条件、股权结构、年限设置为资格条件",
        official_rule_name="不得将从业人员的隐性限制证书设置为资格条件",
        priority="P0",
        target_data_slots=["资格门槛明细", "资格条件明细", "特定资格要求", "证书材料适用阶段"],
        evidence_patterns=["科技型中小企业", "高新技术企业", "从业人员", "规模类型"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
        report_titles=["不得将从业人员的隐性限制证书设置为资格条件", "资格条件可能缺乏履约必要性或带有歧视性门槛"],
        matching_terms=["隐性限制证书", "规模条件", "从业人员", "科技型中小企业", "高新技术企业"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-003",
        official_review_point="不得将供应商规模条件、股权结构、年限设置为资格条件",
        official_rule_name="不得将纳税额的隐性限制证书设置为资格条件",
        priority="P0（暂不测试）",
        target_data_slots=["资格门槛明细", "资格条件明细", "特定资格要求", "证明来源要求"],
        evidence_patterns=["纳税信用A级", "税务部门出具", "纳税额", "纳税信用"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
        report_titles=["不得将纳税额的隐性限制证书设置为资格条件", "资格条件可能缺乏履约必要性或带有歧视性门槛"],
        matching_terms=["隐性限制证书", "纳税额", "纳税信用A级", "税务部门"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-004",
        official_review_point="不得将供应商规模条件、股权结构、年限设置为资格条件",
        official_rule_name="不得将成立年限的隐性限制证书设置为资格条件",
        priority="P0（暂不测试）",
        target_data_slots=["资格门槛明细", "资格条件明细", "特定资格要求"],
        evidence_patterns=["成立满", "设立满", "注册满", "成立年限"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
        report_titles=["不得将成立年限的隐性限制证书设置为资格条件", "资格条件可能缺乏履约必要性或带有歧视性门槛"],
        matching_terms=["隐性限制证书", "成立年限", "成立满", "设立满"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-005",
        official_review_point="不得将特定行业、特定行政区划、特定金额的业绩、奖项作为资格条件",
        official_rule_name="不得将特定行业、特定行政区划、特定金额的业绩作为资格条件",
        priority="P0",
        target_data_slots=["资格门槛明细", "资格条件明细", "评分项明细"],
        evidence_patterns=["同类项目业绩", "类似项目业绩", "深圳市", "广州市", "不少于", "金额"],
        authority_binding_ids=["AUTH-RP-QUAL-004-001"],
        report_titles=["资格业绩要求可能存在地域限定、行业口径过窄或与评分重复"],
        matching_terms=["地域限定", "行业口径", "资格业绩", "同类项目业绩"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-006",
        official_review_point="不得要求中标人承担检测费用",
        official_rule_name="不得将检测费用与检测结果合格性挂钩",
        priority="P0",
        target_data_slots=["验收标准"],
        evidence_patterns=["第三方检测费用", "无论检测结果是否合格", "中标人承担"],
        authority_binding_ids=["AUTH-RP-CONTRACT-013-001"],
        report_titles=["第三方检测费用无论结果均由中标人承担"],
        matching_terms=["检测费用", "检测结果", "无论结果", "中标人承担"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-007",
        official_review_point="不得要求供应商提供特定检测机构（国家行政机关另有规定的除外）出具的检测报告",
        official_rule_name="不得指定非行政机关规定的检测机构",
        priority="P0",
        target_data_slots=["证明来源要求", "是否要求检测报告", "资格条件明细"],
        evidence_patterns=["检测中心", "检测机构", "实验室", "检测报告", "出具"],
        authority_binding_ids=["AUTH-RP-EVID-001-001"],
        report_titles=["证明材料来源可能被限定为特定机构或特定出具口径"],
        matching_terms=["特定检测机构", "检测机构", "检测报告", "特定出具口径"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-008",
        official_review_point="检测报告/检测标准合规性",
        official_rule_name="不得使用不存在的检测标准",
        priority="P0",
        target_data_slots=["技术标准要求"],
        evidence_patterns=["GB/T", "标准", "规范", "不存在的检测标准"],
        authority_binding_ids=["AUTH-RP-REQ-002-001"],
        report_titles=["疑似使用不存在的技术标准"],
        matching_terms=["检测标准", "标准编号", "技术标准有效性", "GB/T"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-009",
        official_review_point="技术参数的区间设置合规性",
        official_rule_name="产品参数设置合规性",
        priority="P2",
        target_data_slots=["技术参数明细"],
        evidence_patterns=["响应时间", "精度", "范围", "区间", "参数值", "单位"],
        authority_binding_ids=["AUTH-RP-REQ-003-001", "AUTH-RP-REQ-004-001"],
        report_titles=["技术参数区间说明不足", "同一技术参数区间说明冲突"],
        matching_terms=["产品参数", "区间设置", "技术参数", "参数合规性"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-010",
        official_review_point="技术参数的区间设置合规性",
        official_rule_name="不得缺失“技术参数区间说明”",
        priority="P2",
        target_data_slots=["技术参数明细"],
        evidence_patterns=["响应时间", "精度", "区间", "范围", "偏离", "取值逻辑"],
        authority_binding_ids=["AUTH-RP-REQ-003-001"],
        report_titles=["技术参数区间说明不足"],
        matching_terms=["区间说明", "参数区间", "偏离判断", "取值逻辑"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-011",
        official_review_point="技术参数的区间设置合规性",
        official_rule_name="不得存在区间说明冲突",
        priority="P2",
        target_data_slots=["技术参数明细"],
        evidence_patterns=["不允许正偏离", "不允许负偏离", "±", "偏差", "允许"],
        authority_binding_ids=["AUTH-RP-REQ-004-001"],
        report_titles=["同一技术参数区间说明冲突"],
        matching_terms=["区间说明冲突", "偏离规则", "允许偏差", "前后冲突"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-012",
        official_review_point="依法设定评审因素",
        official_rule_name="不得将供应商的资产总额设定为评审因素",
        priority="P1",
        target_data_slots=["财务指标加分", "评分项明细"],
        evidence_patterns=["资产总额", "得分", "评分", "分值"],
        authority_binding_ids=["AUTH-RP-SCORE-014-001"],
        report_titles=["资产总额被设为评分因素"],
        matching_terms=["资产总额", "评审因素", "评分因素"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-013",
        official_review_point="依法设定评审因素",
        official_rule_name="不得将供应商的从业人员设定为评审因素",
        priority="P1",
        target_data_slots=["人员评分要求", "评分项明细"],
        evidence_patterns=["从业人员", "得分", "评分", "分值"],
        authority_binding_ids=["AUTH-RP-SCORE-015-001"],
        report_titles=["从业人员被设为评分因素"],
        matching_terms=["从业人员", "评审因素", "评分因素"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-014",
        official_review_point="依法设定评审因素",
        official_rule_name="不得将供应商的纳税额设定为评审因素",
        priority="P1",
        target_data_slots=["财务指标加分", "评分项明细"],
        evidence_patterns=["纳税额", "得分", "评分", "分值"],
        authority_binding_ids=["AUTH-RP-SCORE-016-001"],
        report_titles=["纳税额被设为评分因素"],
        matching_terms=["纳税额", "评审因素", "评分因素"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-015",
        official_review_point="依法设定评审因素",
        official_rule_name="不得将供应商的成立年限设定为评审因素",
        priority="P1",
        target_data_slots=["评分项明细", "行业相关性存疑评分项"],
        evidence_patterns=["成立年限", "成立满", "得分", "评分", "分值"],
        authority_binding_ids=["AUTH-RP-SCORE-017-001"],
        report_titles=["成立年限被设为评分因素", "经营年限被设为评分因素"],
        matching_terms=["成立年限", "经营年限", "评审因素", "评分因素"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-016",
        official_review_point="依法设定评审因素",
        official_rule_name="不得将国务院已明令取消的资质、资格、认证作为评审因素",
        priority="P0",
        target_data_slots=["准入类证书评分项", "评分项明细"],
        evidence_patterns=["许可证", "行政许可", "作业人员证书", "得分"],
        authority_binding_ids=["AUTH-RP-SCORE-025-001"],
        report_titles=["不得将准入类、行政许可类资格职业证书设置为评分项"],
        matching_terms=["已明令取消", "资格职业证书", "行政许可", "准入类"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-017",
        official_review_point="依法设定评审因素",
        official_rule_name="不得使用主观描述来要求供应商所投产品",
        priority="P2",
        target_data_slots=["技术服务可验证性信号", "技术参数明细"],
        evidence_patterns=["操作体验", "友好美观", "设计美观", "人体工程学设计"],
        authority_binding_ids=["AUTH-RP-REQ-005-001"],
        report_titles=["技术要求存在主观描述"],
        matching_terms=["主观描述", "体验", "美观", "客观指标"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-018",
        official_review_point="依法设定评审因素",
        official_rule_name="证书设置的合理性",
        priority="P0",
        target_data_slots=["体系认证范围要求", "准入类证书评分项", "评分项明细"],
        evidence_patterns=["认证范围", "认证证书", "管理体系认证", "许可证", "证书"],
        authority_binding_ids=["AUTH-RP-SCORE-025-001", "AUTH-RP-SCORE-005-001"],
        report_titles=[
            "体系认证证书不得要求特定认证范围",
            "不得将准入类、行政许可类资格职业证书设置为评分项",
            "特定资质或证书要求超必要限度",
        ],
        matching_terms=["证书设置", "认证范围", "证书合理性", "特定资质"],
    ),
    OfficialRuleProfile(
        official_rule_id="OFFICIAL-SZDL-019",
        official_review_point="依法设定价格分值",
        official_rule_name="采用综合评分法评标的，价格分（必须）采用低价优先法",
        priority="P0",
        target_data_slots=["价格分计算方法", "评分方法", "价格分"],
        evidence_patterns=["价格分计算方法", "中间价优先法", "平均值作为评标基准价", "低价优先法"],
        authority_binding_ids=["AUTH-RP-SCORE-018-001", "AUTH-RP-SCORE-026-001"],
        report_titles=["综合评分法价格分未采用低价优先法", "依法设定价格分值"],
        matching_terms=["低价优先法", "价格分", "综合评分法", "评标基准价"],
    ),
]


OFFICIAL_RULE_BY_NAME: dict[str, OfficialRuleProfile] = {
    profile.official_rule_name: profile for profile in OFFICIAL_RULE_PROFILES
}


def build_title_synonym_groups() -> dict[str, tuple[str, ...]]:
    groups: dict[str, tuple[str, ...]] = {}
    for profile in OFFICIAL_RULE_PROFILES:
        merged = list(dict.fromkeys([*profile.report_titles, *profile.matching_terms]))
        groups[profile.official_rule_name] = tuple(merged)
        if profile.official_review_point not in groups:
            groups[profile.official_review_point] = tuple(merged)
    return groups
