from __future__ import annotations

from .models import ReviewPointContract


REVIEW_POINT_CONTRACTS: list[ReviewPointContract] = [
    ReviewPointContract(
        point_id="RP-QUAL-003",
        title="资格条件可能缺乏履约必要性或带有歧视性门槛",
        description="审查与履约能力无直接关联、可能变相限制竞争的资格门槛。",
        risk_family="qualification",
        legal_theme="资格必要性与公平竞争",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["qualification", "scoring"],
        primary_review_types=["资格", "评分"],
        required_fact_types=["qualification_requirement", "certificate_requirement"],
        supporting_fact_types=["qualification_material_requirement", "cross_clause_conflict_signal"],
        activation_rule_ids=[
            "RULE-QUAL-CERT-001",
            "RULE-QUAL-TAX-001",
            "RULE-QUAL-AGE-001",
        ],
        required_fields=["特定资格要求", "资格条件明细", "资格门槛明细"],
        enhancement_fields=["证明来源要求", "证书材料适用阶段"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_reference_only_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
        severity_policy="high",
        report_group="资格与公平竞争",
        report_priority=10,
    ),
    ReviewPointContract(
        point_id="RP-QUAL-004",
        title="资格业绩要求可能存在地域限定、行业口径过窄或与评分重复",
        description="审查资格业绩是否收窄地域、行业范围，或与评分项重复设门槛。",
        risk_family="qualification",
        legal_theme="资格业绩必要性与公平竞争",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["qualification", "scoring"],
        primary_review_types=["资格", "评分"],
        required_fact_types=["performance_requirement"],
        supporting_fact_types=["scoring_factor", "cross_clause_conflict_signal"],
        activation_rule_ids=[
            "RULE-QUAL-PERF-REGION-001",
            "RULE-QUAL-PERF-DUP-001",
        ],
        required_fields=["资格条件明细", "资格门槛明细", "评分项明细"],
        enhancement_fields=["采购包划分说明", "行业相关性存疑评分项"],
        evidence_policy="cross_clause_evidence_required",
        quality_gate_policy="weak_zone_only_manual",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-QUAL-004-001"],
        severity_policy="high",
        report_group="资格与公平竞争",
        report_priority=11,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-005",
        title="行业无关证书或财务指标被纳入评分",
        description="审查评分项是否引入与采购需求和履约质量无直接关联的证书或财务指标。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring", "qualification", "technical", "business"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=["certificate_requirement", "evidence_source_requirement"],
        activation_rule_ids=[
            "RULE-SCORE-CERT-001",
            "RULE-SCORE-FIN-001",
        ],
        required_fields=["评分方法", "评分项明细", "行业相关性存疑评分项"],
        enhancement_fields=["证书材料适用阶段", "检测报告适用阶段"],
        evidence_policy="table_and_text_alignment_required",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-005-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=20,
    ),
    ReviewPointContract(
        point_id="RP-EVID-001",
        title="证明材料来源可能被限定为特定机构或特定出具口径",
        description="审查检测报告、证明材料是否被限定为特定检测中心、机构或唯一出具来源。",
        risk_family="qualification",
        legal_theme="证明材料来源限制与公平竞争",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["qualification", "technical"],
        primary_review_types=["资格", "技术"],
        required_fact_types=["evidence_source_requirement"],
        supporting_fact_types=["qualification_material_requirement", "technical_parameter"],
        activation_rule_ids=["RULE-EVID-SOURCE-001"],
        required_fields=["证明来源要求", "资格条件明细"],
        enhancement_fields=["是否要求检测报告", "证书材料适用阶段"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="named_institution_quote_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-EVID-001-001"],
        severity_policy="high",
        report_group="证明材料与检测要求风险",
        report_priority=21,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-009",
        title="验收标准存在优胜原则或单方弹性判断",
        description="审查验收标准是否依赖采购人单方解释、优胜原则或弹性判断。",
        risk_family="contract",
        legal_theme="合同公平性与验收明确性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["contract"],
        primary_review_types=["合同"],
        required_fact_types=["acceptance_term"],
        supporting_fact_types=["payment_term", "breach_term"],
        activation_rule_ids=["RULE-CONTRACT-ACCEPT-001"],
        required_fields=["验收标准"],
        enhancement_fields=["付款节点", "违约责任"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-009-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=30,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-011",
        title="验收与付款/考核/满意度联动不当",
        description="审查付款是否被验收、考核或满意度条款以主观方式控制。",
        risk_family="contract",
        legal_theme="合同公平性与付款客观性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["contract"],
        primary_review_types=["合同"],
        required_fact_types=["payment_term", "acceptance_term"],
        supporting_fact_types=["breach_term"],
        activation_rule_ids=["RULE-CONTRACT-PAY-001"],
        required_fields=["付款节点", "验收标准"],
        enhancement_fields=["考核条款", "满意度条款", "扣款条款"],
        evidence_policy="context_linkage_required",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-011-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=31,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-012",
        title="履约保证金转质量保证金或长期无息占压",
        description="审查履约担保条款是否演变为质量保证金长期无息占压。",
        risk_family="contract",
        legal_theme="合同担保适度性与资金占压",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["contract"],
        primary_review_types=["合同"],
        required_fact_types=["acceptance_term"],
        supporting_fact_types=["payment_term"],
        activation_rule_ids=["RULE-CONTRACT-GUAR-001"],
        required_fields=["履约保证金"],
        enhancement_fields=["付款节点", "质保期"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-012-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=32,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-013",
        title="第三方检测费用无论结果均由中标人承担",
        description="审查第三方检测费用是否被不区分结果和责任地转嫁给中标人。",
        risk_family="contract",
        legal_theme="验收费用分配公平性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["contract"],
        primary_review_types=["合同"],
        required_fact_types=["acceptance_term"],
        supporting_fact_types=["payment_term"],
        activation_rule_ids=["RULE-CONTRACT-TEST-001"],
        required_fields=["验收标准"],
        enhancement_fields=["付款节点"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-013-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=33,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-014",
        title="采购人应当在收到发票后N个工作日内完成资金支付/采购人应当在收到发票后N个工作日或Y日内完成资金支付",
        description="审查采购人付款条款是否以收到发票为起点，但支付时限明显偏离常见政府采购支付要求。",
        risk_family="contract",
        legal_theme="合同支付时限",
        applicable_procurement_kinds=["service", "mixed", "unknown"],
        target_zone_types=["contract"],
        primary_review_types=["合同"],
        required_fact_types=["payment_term"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-CONTRACT-PAYTIME-001"],
        required_fields=["付款时限", "付款节点"],
        enhancement_fields=["项目属性"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-014-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=34,
    ),
    ReviewPointContract(
        point_id="RP-CONTRACT-015",
        title="服务合同履行期限不得超过36个月",
        description="审查服务项目合同履行期限是否超过 36 个月。",
        risk_family="contract",
        legal_theme="服务期限边界",
        applicable_procurement_kinds=["service", "mixed", "unknown"],
        target_zone_types=["administrative_info", "contract"],
        primary_review_types=["合同"],
        required_fact_types=["payment_term", "delivery_requirement", "qualification_requirement"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-CONTRACT-SERVPERIOD-001"],
        required_fields=["服务期限月数", "合同履行期限", "项目属性"],
        enhancement_fields=["采购标的"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_example_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-CONTRACT-015-001"],
        severity_policy="high",
        report_group="合同履约风险",
        report_priority=35,
    ),
    ReviewPointContract(
        point_id="RP-COMP-001",
        title="以预算金额比例设最低报价门槛",
        description="审查是否以预算金额固定比例直接设置最低报价门槛并否决投标。",
        risk_family="competition",
        legal_theme="报价审查边界与公平竞争",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["business"],
        primary_review_types=["商务", "报价"],
        required_fact_types=["delivery_requirement"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-PRICE-FLOOR-001"],
        required_fields=["预算金额"],
        enhancement_fields=["最高限价"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="named_rule_hit_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-COMP-001-001"],
        severity_policy="high",
        report_group="限制竞争风险",
        report_priority=15,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-019",
        title="注册资本被设为评分因素",
        description="审查评分项是否直接以供应商注册资本作为加分条件。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-REGCAP-001"],
        required_fields=["财务指标加分", "评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-019-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=24,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-020",
        title="营业收入被设为评分因素",
        description="审查评分项是否直接以供应商营业收入作为加分条件。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-REVENUE-001"],
        required_fields=["财务指标加分", "评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-020-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=25,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-021",
        title="净利润或利润被设为评分因素",
        description="审查评分项是否直接以供应商净利润、利润或利润率作为加分条件。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-PROFIT-001"],
        required_fields=["财务指标加分", "评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-021-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=26,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-022",
        title="股权结构被设为评分因素",
        description="审查评分项是否把供应商股权结构、资本背景作为偏好性加分条件。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-SHARE-001"],
        required_fields=["评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-022-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=27,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-023",
        title="经营年限被设为评分因素",
        description="审查评分项是否直接以供应商经营年限、相关行业从业经验作为加分条件。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-OPERAGE-001"],
        required_fields=["评分项明细", "行业相关性存疑评分项"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-023-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=28,
    ),
    ReviewPointContract(
        point_id="RP-QUAL-005",
        title="不得限定供应商组织形式",
        description="审查资格门槛是否直接排斥个体工商户等组织形式。",
        risk_family="qualification",
        legal_theme="组织形式中立",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["qualification"],
        primary_review_types=["资格"],
        required_fact_types=["qualification_requirement"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-QUAL-ORGFORM-001"],
        required_fields=["供应商组织形式限制", "资格门槛明细"],
        enhancement_fields=["资格条件明细"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="template_or_reference_only_filtered",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-QUAL-005-001"],
        severity_policy="high",
        report_group="资格与公平竞争",
        report_priority=12,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-024",
        title="体系认证证书不得要求特定认证范围",
        description="审查评分项是否对体系认证证书设置特定认证范围要求。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-CERTSCOPE-001"],
        required_fields=["体系认证范围要求", "评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-024-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=29,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-025",
        title="不得将准入类、行政许可类资格职业证书设置为评分项",
        description="审查评分项是否将行政许可、准入类职业资格证书继续作为加分项。",
        risk_family="scoring",
        legal_theme="评分相关性",
        applicable_procurement_kinds=["goods", "service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-ADMINLICENSE-001"],
        required_fields=["准入类证书评分项", "评分项明细"],
        enhancement_fields=["评分方法"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-025-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=30,
    ),
    ReviewPointContract(
        point_id="RP-SCORE-026",
        title="服务项目价格分值权重低于10%",
        description="审查服务项目综合评分中价格因素权重是否低于 10%。",
        risk_family="scoring",
        legal_theme="价格权重合理性",
        applicable_procurement_kinds=["service", "mixed", "unknown"],
        target_zone_types=["scoring"],
        primary_review_types=["评分"],
        required_fact_types=["scoring_factor"],
        supporting_fact_types=[],
        activation_rule_ids=["RULE-SCORE-PRICEWEIGHT-001"],
        required_fields=["价格权重", "项目属性"],
        enhancement_fields=["评分方法", "价格分"],
        evidence_policy="single_direct_quote_sufficient",
        quality_gate_policy="scoring_table_preferred",
        manual_boundary_policy="authority_driven",
        authority_binding_ids=["AUTH-RP-SCORE-026-001"],
        severity_policy="high",
        report_group="评分不规范风险",
        report_priority=31,
    ),
]


CONTRACT_INDEX: dict[str, ReviewPointContract] = {
    item.point_id: item for item in REVIEW_POINT_CONTRACTS
}


def get_review_point_contract(point_id: str) -> ReviewPointContract | None:
    return CONTRACT_INDEX.get(point_id.strip())


def list_review_point_contracts() -> list[ReviewPointContract]:
    return list(REVIEW_POINT_CONTRACTS)
