from __future__ import annotations

from .models import RuleDefinition


RULE_DEFINITIONS: list[RuleDefinition] = [
    RuleDefinition(
        rule_id="RULE-QUAL-CERT-001",
        version="v1",
        name="非必要资格证书门槛",
        point_id="RP-QUAL-003",
        rule_type="soft_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification"],
        applicable_fact_types=["qualification_requirement", "certificate_requirement"],
        trigger_patterns=["高新技术企业", "科技型中小企业", "纳税信用A级"],
        required_fact_slots=["object_text"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法定许可", "行业强制资质", "安全保密资质"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该资格门槛是否具有直接履约必要性"],
        remedy_template_ids=["REMEDY-QUAL-NECESSITY-001"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
    ),
    RuleDefinition(
        rule_id="RULE-QUAL-TAX-001",
        version="v1",
        name="纳税信用等级资格门槛",
        point_id="RP-QUAL-003",
        rule_type="soft_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification"],
        applicable_fact_types=["qualification_requirement", "qualification_material_requirement"],
        trigger_patterns=["纳税信用A级", "税务部门出具的证明"],
        required_fact_slots=["object_text"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法律法规明确要求"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["纳税信用等级是否构成超必要门槛"],
        remedy_template_ids=["REMEDY-QUAL-TAX-001"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
    ),
    RuleDefinition(
        rule_id="RULE-QUAL-AGE-001",
        version="v1",
        name="成立年限资格门槛",
        point_id="RP-QUAL-003",
        rule_type="soft_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification"],
        applicable_fact_types=["qualification_requirement"],
        trigger_patterns=["成立满", "设立满", "注册满"],
        required_fact_slots=["constraint_value"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法律法规明确要求", "持续经营许可法定前提"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该成立年限要求是否存在法定或直接履约依据"],
        remedy_template_ids=["REMEDY-QUAL-AGE-001"],
        authority_binding_ids=["AUTH-RP-QUAL-003-001"],
    ),
    RuleDefinition(
        rule_id="RULE-QUAL-PERF-REGION-001",
        version="v1",
        name="地域或行业口径收窄的资格业绩要求",
        point_id="RP-QUAL-004",
        rule_type="soft_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification"],
        applicable_fact_types=["performance_requirement"],
        trigger_patterns=["深圳市", "广州市", "本地", "同类项目业绩", "医疗器械行业"],
        required_fact_slots=["region", "industry_scope", "min_count"],
        evidence_requirements=["direct_quote_required", "cross_clause_alignment_required"],
        exception_patterns=["现场连续运行", "应急保障", "明确客观场景需要"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该地域或行业口径是否具有客观履约必要性"],
        remedy_template_ids=["REMEDY-QUAL-PERF-001"],
        authority_binding_ids=["AUTH-RP-QUAL-004-001"],
    ),
    RuleDefinition(
        rule_id="RULE-QUAL-PERF-DUP-001",
        version="v1",
        name="资格业绩与评分重复设门槛",
        point_id="RP-QUAL-004",
        rule_type="cross_clause_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification", "scoring"],
        applicable_fact_types=["performance_requirement", "scoring_factor", "cross_clause_conflict_signal"],
        trigger_patterns=["同类业绩", "类似项目业绩", "业绩不少于"],
        required_fact_slots=["object_text"],
        evidence_requirements=["cross_clause_alignment_required"],
        exception_patterns=[],
        severity_hint="high",
        default_disposition="warning",
        llm_assist_policy="low_confidence_only",
        llm_questions=["资格业绩要求与评分业绩项是否实质重复"],
        remedy_template_ids=["REMEDY-QUAL-DUP-001"],
        authority_binding_ids=["AUTH-RP-QUAL-004-001"],
    ),
    RuleDefinition(
        rule_id="RULE-EVID-SOURCE-001",
        version="v1",
        name="指定机构或出具来源限制",
        point_id="RP-EVID-001",
        rule_type="soft_rule",
        risk_family="qualification",
        applicable_zone_types=["qualification", "technical"],
        applicable_fact_types=["evidence_source_requirement", "qualification_material_requirement", "technical_parameter"],
        trigger_patterns=["检测中心", "检测机构", "实验室", "税务部门", "研究院"],
        required_fact_slots=["evidence_source", "source_category", "evidence_kind"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法律法规明确要求", "国家强制检验检疫", "行业主管部门强制要求"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该证明材料来源限制是否具有法定或直接履约必要性"],
        remedy_template_ids=["REMEDY-EVID-SOURCE-001"],
        authority_binding_ids=["AUTH-RP-EVID-001-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-CERT-001",
        version="v1",
        name="行业无关证书评分",
        point_id="RP-SCORE-005",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor", "certificate_requirement"],
        trigger_patterns=["证书", "检测报告", "CMA", "CNAS", "软件企业认定证书", "ITSS"],
        required_fact_slots=["score", "scoring_item_type"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["与采购标的直接相关", "履约质量直接相关"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该证书或报告是否与采购需求和履约质量直接相关"],
        remedy_template_ids=["REMEDY-SCORE-CERT-001"],
        authority_binding_ids=["AUTH-RP-SCORE-005-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-FIN-001",
        version="v1",
        name="财务指标评分",
        point_id="RP-SCORE-005",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["营业收入", "利润率", "财务报告", "资产规模"],
        required_fact_slots=["score", "scoring_item_type"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["确有履约保障必要性且量化明确"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该财务指标是否对履约质量具有直接说明作用"],
        remedy_template_ids=["REMEDY-SCORE-FIN-001"],
        authority_binding_ids=["AUTH-RP-SCORE-005-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-REGCAP-001",
        version="v1",
        name="注册资本评分",
        point_id="RP-SCORE-019",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["注册资本", "registered_capital"],
        required_fact_slots=["score", "metric_name"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["注册资本与法定许可直接绑定且已充分论证必要性"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["注册资本指标是否与本项目履约能力具有直接必要联系"],
        remedy_template_ids=["REMEDY-SCORE-REGCAP-001"],
        authority_binding_ids=["AUTH-RP-SCORE-019-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-REVENUE-001",
        version="v1",
        name="营业收入评分",
        point_id="RP-SCORE-020",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["营业收入", "revenue"],
        required_fact_slots=["score", "metric_name"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["采购人能够证明营业收入与履约规模直接对应且论证充分"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["营业收入作为评分因素是否属于以企业规模替代项目履约能力"],
        remedy_template_ids=["REMEDY-SCORE-REVENUE-001"],
        authority_binding_ids=["AUTH-RP-SCORE-020-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-PROFIT-001",
        version="v1",
        name="利润或净利润评分",
        point_id="RP-SCORE-021",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["净利润", "利润率", "利润", "net_profit", "profit"],
        required_fact_slots=["score", "metric_name"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["采购人能够证明利润指标与法定监管或直接履约风险紧密相关"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["利润或净利润指标是否属于以经营结果替代项目履约能力"],
        remedy_template_ids=["REMEDY-SCORE-PROFIT-001"],
        authority_binding_ids=["AUTH-RP-SCORE-021-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-SHARE-001",
        version="v1",
        name="股权结构评分",
        point_id="RP-SCORE-022",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["股东", "股权结构", "资本背景", "国有投资主体", "产业资本", "shareholding"],
        required_fact_slots=["score", "metric_name"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["股权背景与法定特许经营资格直接绑定"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["股权结构或资本背景是否被不当作为评分偏好"],
        remedy_template_ids=["REMEDY-SCORE-SHARE-001"],
        authority_binding_ids=["AUTH-RP-SCORE-022-001"],
    ),
    RuleDefinition(
        rule_id="RULE-SCORE-OPERAGE-001",
        version="v1",
        name="经营年限评分",
        point_id="RP-SCORE-023",
        rule_type="soft_rule",
        risk_family="scoring",
        applicable_zone_types=["scoring"],
        applicable_fact_types=["scoring_factor"],
        trigger_patterns=["经营年限", "从业经验", "operating_age"],
        required_fact_slots=["score", "metric_name"],
        evidence_requirements=["table_row_preferred"],
        exception_patterns=["条款实际针对拟投入人员执业年限而非供应商自身历史"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["经营年限或行业从业经验是否被不当作为供应商评分因素"],
        remedy_template_ids=["REMEDY-SCORE-OPERAGE-001"],
        authority_binding_ids=["AUTH-RP-SCORE-023-001"],
    ),
    RuleDefinition(
        rule_id="RULE-CONTRACT-ACCEPT-001",
        version="v1",
        name="验收标准弹性判断",
        point_id="RP-CONTRACT-009",
        rule_type="hard_rule",
        risk_family="contract",
        applicable_zone_types=["contract"],
        applicable_fact_types=["acceptance_term"],
        trigger_patterns=["以采购人最终解释为准", "优胜原则", "采购人认为合格", "单方判断"],
        required_fact_slots=["decision_mode", "contract_control"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["行业主管部门强制验收规则", "第三方检测强制要求"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该验收条款是否属于法定强制标准下的例外表达"],
        remedy_template_ids=["REMEDY-CONTRACT-ACCEPT-001"],
        authority_binding_ids=["AUTH-RP-CONTRACT-009-001"],
    ),
    RuleDefinition(
        rule_id="RULE-CONTRACT-PAY-001",
        version="v1",
        name="付款与验收考核联动控制",
        point_id="RP-CONTRACT-011",
        rule_type="soft_rule",
        risk_family="contract",
        applicable_zone_types=["contract"],
        applicable_fact_types=["payment_term", "acceptance_term"],
        trigger_patterns=["验收付款联动", "考核付款联动", "payment_control", "assessment_or_satisfaction"],
        required_fact_slots=["payment_linkage", "contract_control"],
        evidence_requirements=["direct_quote_required", "context_linkage_preferred"],
        exception_patterns=["法定分期验收付款机制", "客观量化考核且与付款比例明确对应"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["付款是否被主观验收、考核或满意度机制不当控制"],
        remedy_template_ids=["REMEDY-CONTRACT-LINKAGE-001"],
        authority_binding_ids=["AUTH-RP-CONTRACT-011-001"],
    ),
    RuleDefinition(
        rule_id="RULE-CONTRACT-GUAR-001",
        version="v1",
        name="履约担保转质量保证金并形成资金占压",
        point_id="RP-CONTRACT-012",
        rule_type="hard_rule",
        risk_family="contract",
        applicable_zone_types=["contract"],
        applicable_fact_types=["acceptance_term"],
        trigger_patterns=["履约转质保", "guarantee_fund_occupation", "银行转账", "无息退还"],
        required_fact_slots=["guarantee_transform", "guarantee_ratio", "payment_method", "refund_policy"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法定质保金制度另有明确规定"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该保证金安排是否将履约担保异化为长期质量保证金占压"],
        remedy_template_ids=["REMEDY-CONTRACT-GUARANTEE-001"],
        authority_binding_ids=["AUTH-RP-CONTRACT-012-001"],
    ),
    RuleDefinition(
        rule_id="RULE-CONTRACT-TEST-001",
        version="v1",
        name="第三方检测费用结果无关转嫁",
        point_id="RP-CONTRACT-013",
        rule_type="hard_rule",
        risk_family="contract",
        applicable_zone_types=["contract"],
        applicable_fact_types=["acceptance_term"],
        trigger_patterns=["第三方检测费用", "检测费用转嫁", "结果无关承担", "test_cost_allocation"],
        required_fact_slots=["cost_bearer", "result_condition", "contract_control"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["法律法规强制由供应商承担且结果条件明确"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["检测费用是否在不区分责任和结果的情况下被一概转嫁给中标人"],
        remedy_template_ids=["REMEDY-CONTRACT-TEST-COST-001"],
        authority_binding_ids=["AUTH-RP-CONTRACT-013-001"],
    ),
    RuleDefinition(
        rule_id="RULE-PRICE-FLOOR-001",
        version="v1",
        name="以预算比例设置刚性最低报价门槛",
        point_id="RP-COMP-001",
        rule_type="hard_rule",
        risk_family="competition",
        applicable_zone_types=["business"],
        applicable_fact_types=["delivery_requirement"],
        trigger_patterns=["预算比例最低价", "hard_price_floor", "预算金额", "无效投标"],
        required_fact_slots=["price_floor_ratio", "price_floor_base", "rejection_trigger", "pricing_control"],
        evidence_requirements=["direct_quote_required"],
        exception_patterns=["依法采用异常低价审查说明机制"],
        severity_hint="high",
        default_disposition="manual_review_required",
        llm_assist_policy="boundary_only",
        llm_questions=["该价格条款是否以刚性最低报价比例直接否决投标"],
        remedy_template_ids=["REMEDY-PRICE-FLOOR-001"],
        authority_binding_ids=["AUTH-RP-COMP-001-001"],
    ),
]


RULE_INDEX: dict[str, RuleDefinition] = {item.rule_id: item for item in RULE_DEFINITIONS}


def get_rule_definition(rule_id: str) -> RuleDefinition | None:
    return RULE_INDEX.get(rule_id.strip())


def list_rule_definitions() -> list[RuleDefinition]:
    return list(RULE_DEFINITIONS)


def list_rules_for_point(point_id: str) -> list[RuleDefinition]:
    normalized = point_id.strip()
    return [item for item in RULE_DEFINITIONS if item.point_id == normalized]
